version: "3.9"
services:
  chatgpt-next-web:
    profiles: [ "no-proxy" ]
    container_name: chatgpt-next-web
    image: yidadaa/chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=sk-test-123123-xxxx
      - CODE=123123123
      - GOOGLE_API_KEY=
      - BASE_URL=
      - OPENAI_ORG_ID=
      - HIDE_USER_API_KEY=
      - DISABLE_GPT4=
      - ENABLE_BALANCE_QUERY=
      - DISABLE_FAST_LINK=
      - OPENAI_SB=

  chatgpt-next-web-proxy:
    profiles: [ "proxy" ]
    container_name: chatgpt-next-web-proxy
    image: yidadaa/chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=sk-test-123123-xxxx
      - GOOGLE_API_KEY=
      - CODE=123123123
      - PROXY_URL=
      - BASE_URL=
      - OPENAI_ORG_ID=
      - HIDE_USER_API_KEY=
      - DISABLE_GPT4=
      - ENABLE_BALANCE_QUERY=
      - DISABLE_FAST_LINK=
      - OPENAI_SB=